echo "N,K,Time(usec),Accuracy" > test/results.csv
./bin/int_test-1 >> test/results.csv
./bin/int_test-2 >> test/results.csv
./bin/int_test-3 >> test/results.csv
./bin/int_test-4 >> test/results.csv
./bin/int_test-5 >> test/results.csv
./bin/int_test-6 >> test/results.csv
./bin/int_test-7 >> test/results.csv
./bin/int_test-8 >> test/results.csv
./bin/int_test-9 >> test/results.csv
./bin/int_test-10 >> test/results.csv
./bin/int_test-11 >> test/results.csv
./bin/int_test-12 >> test/results.csv
./bin/int_test-13 >> test/results.csv
./bin/int_test-14 >> test/results.csv
./bin/int_test-15 >> test/results.csv
./bin/int_test-16 >> test/results.csv
./bin/int_test-17 >> test/results.csv
./bin/int_test-18 >> test/results.csv
./bin/int_test-19 >> test/results.csv
./bin/int_test-20 >> test/results.csv
./bin/int_test-21 >> test/results.csv
./bin/int_test-22 >> test/results.csv
./bin/int_test-23 >> test/results.csv
./bin/int_test-24 >> test/results.csv
./bin/int_test-25 >> test/results.csv
./bin/int_test-26 >> test/results.csv
./bin/int_test-27 >> test/results.csv
./bin/int_test-28 >> test/results.csv
./bin/int_test-29 >> test/results.csv
./bin/int_test-30 >> test/results.csv
./bin/int_test-31 >> test/results.csv
./bin/int_test-32 >> test/results.csv
./bin/int_test-33 >> test/results.csv
./bin/int_test-34 >> test/results.csv
./bin/int_test-35 >> test/results.csv
./bin/int_test-36 >> test/results.csv
./bin/int_test-37 >> test/results.csv
./bin/int_test-38 >> test/results.csv
./bin/int_test-39 >> test/results.csv
./bin/int_test-40 >> test/results.csv
./bin/int_test-41 >> test/results.csv
./bin/int_test-42 >> test/results.csv
./bin/int_test-43 >> test/results.csv
./bin/int_test-44 >> test/results.csv
./bin/int_test-45 >> test/results.csv
./bin/int_test-46 >> test/results.csv
./bin/int_test-47 >> test/results.csv
./bin/int_test-48 >> test/results.csv
./bin/int_test-49 >> test/results.csv
