echo "N,K,Time(usec)" > test/results.csv
./bin/int_test-1 >> test/results.csv
./bin/int_test-2 >> test/results.csv
./bin/int_test-3 >> test/results.csv
./bin/int_test-4 >> test/results.csv
./bin/int_test-5 >> test/results.csv
./bin/int_test-6 >> test/results.csv
./bin/int_test-7 >> test/results.csv
./bin/int_test-8 >> test/results.csv
./bin/int_test-9 >> test/results.csv
./bin/int_test-10 >> test/results.csv
./bin/int_test-11 >> test/results.csv
./bin/int_test-12 >> test/results.csv
./bin/int_test-13 >> test/results.csv
./bin/int_test-14 >> test/results.csv
./bin/int_test-15 >> test/results.csv
./bin/int_test-16 >> test/results.csv
./bin/int_test-17 >> test/results.csv
./bin/int_test-18 >> test/results.csv
./bin/int_test-19 >> test/results.csv
./bin/int_test-20 >> test/results.csv
./bin/int_test-21 >> test/results.csv
./bin/int_test-22 >> test/results.csv
./bin/int_test-23 >> test/results.csv
./bin/int_test-24 >> test/results.csv
./bin/int_test-25 >> test/results.csv
./bin/int_test-26 >> test/results.csv
./bin/int_test-27 >> test/results.csv
./bin/int_test-28 >> test/results.csv
./bin/int_test-29 >> test/results.csv
./bin/int_test-30 >> test/results.csv
./bin/int_test-31 >> test/results.csv
./bin/int_test-32 >> test/results.csv
./bin/int_test-33 >> test/results.csv
./bin/int_test-34 >> test/results.csv
./bin/int_test-35 >> test/results.csv
./bin/int_test-36 >> test/results.csv
./bin/int_test-37 >> test/results.csv
./bin/int_test-38 >> test/results.csv
./bin/int_test-39 >> test/results.csv
./bin/int_test-40 >> test/results.csv
./bin/int_test-41 >> test/results.csv
./bin/int_test-42 >> test/results.csv
./bin/int_test-43 >> test/results.csv
./bin/int_test-44 >> test/results.csv
./bin/int_test-45 >> test/results.csv
./bin/int_test-46 >> test/results.csv
./bin/int_test-47 >> test/results.csv
./bin/int_test-48 >> test/results.csv
./bin/int_test-49 >> test/results.csv
./bin/int_test-50 >> test/results.csv
./bin/int_test-51 >> test/results.csv
./bin/int_test-52 >> test/results.csv
./bin/int_test-53 >> test/results.csv
./bin/int_test-54 >> test/results.csv
./bin/int_test-55 >> test/results.csv
./bin/int_test-56 >> test/results.csv
./bin/int_test-57 >> test/results.csv
./bin/int_test-58 >> test/results.csv
./bin/int_test-59 >> test/results.csv
./bin/int_test-60 >> test/results.csv
./bin/int_test-61 >> test/results.csv
./bin/int_test-62 >> test/results.csv
./bin/int_test-63 >> test/results.csv
./bin/int_test-64 >> test/results.csv
./bin/int_test-65 >> test/results.csv
./bin/int_test-66 >> test/results.csv
./bin/int_test-67 >> test/results.csv
./bin/int_test-68 >> test/results.csv
./bin/int_test-69 >> test/results.csv
./bin/int_test-70 >> test/results.csv
./bin/int_test-71 >> test/results.csv
./bin/int_test-72 >> test/results.csv
./bin/int_test-73 >> test/results.csv
./bin/int_test-74 >> test/results.csv
./bin/int_test-75 >> test/results.csv
./bin/int_test-76 >> test/results.csv
./bin/int_test-77 >> test/results.csv
./bin/int_test-78 >> test/results.csv
./bin/int_test-79 >> test/results.csv
./bin/int_test-80 >> test/results.csv
./bin/int_test-81 >> test/results.csv
./bin/int_test-82 >> test/results.csv
./bin/int_test-83 >> test/results.csv
./bin/int_test-84 >> test/results.csv
./bin/int_test-85 >> test/results.csv
./bin/int_test-86 >> test/results.csv
./bin/int_test-87 >> test/results.csv
./bin/int_test-88 >> test/results.csv
./bin/int_test-89 >> test/results.csv
./bin/int_test-90 >> test/results.csv
./bin/int_test-91 >> test/results.csv
./bin/int_test-92 >> test/results.csv
./bin/int_test-93 >> test/results.csv
./bin/int_test-94 >> test/results.csv
./bin/int_test-95 >> test/results.csv
./bin/int_test-96 >> test/results.csv
./bin/int_test-97 >> test/results.csv
./bin/int_test-98 >> test/results.csv
./bin/int_test-99 >> test/results.csv
./bin/int_test-100 >> test/results.csv
./bin/int_test-101 >> test/results.csv
./bin/int_test-102 >> test/results.csv
./bin/int_test-103 >> test/results.csv
./bin/int_test-104 >> test/results.csv
./bin/int_test-105 >> test/results.csv
