echo "N,K,M,Time(usec)" > test/results.csv
./bin/int_test-1 >> test/results.csv
./bin/int_test-2 >> test/results.csv
./bin/int_test-3 >> test/results.csv
./bin/int_test-4 >> test/results.csv
./bin/int_test-5 >> test/results.csv
./bin/int_test-6 >> test/results.csv
./bin/int_test-7 >> test/results.csv
./bin/int_test-8 >> test/results.csv
./bin/int_test-9 >> test/results.csv
./bin/int_test-10 >> test/results.csv
./bin/int_test-11 >> test/results.csv
./bin/int_test-12 >> test/results.csv
./bin/int_test-13 >> test/results.csv
./bin/int_test-14 >> test/results.csv
./bin/int_test-15 >> test/results.csv
./bin/int_test-16 >> test/results.csv
./bin/int_test-17 >> test/results.csv
./bin/int_test-18 >> test/results.csv
./bin/int_test-19 >> test/results.csv
./bin/int_test-20 >> test/results.csv
./bin/int_test-21 >> test/results.csv
./bin/int_test-22 >> test/results.csv
./bin/int_test-23 >> test/results.csv
./bin/int_test-24 >> test/results.csv
./bin/int_test-25 >> test/results.csv
./bin/int_test-26 >> test/results.csv
./bin/int_test-27 >> test/results.csv
./bin/int_test-28 >> test/results.csv
./bin/int_test-29 >> test/results.csv
./bin/int_test-30 >> test/results.csv
./bin/int_test-31 >> test/results.csv
./bin/int_test-32 >> test/results.csv
./bin/int_test-33 >> test/results.csv
./bin/int_test-34 >> test/results.csv
./bin/int_test-35 >> test/results.csv
./bin/int_test-36 >> test/results.csv
./bin/int_test-37 >> test/results.csv
./bin/int_test-38 >> test/results.csv
./bin/int_test-39 >> test/results.csv
./bin/int_test-40 >> test/results.csv
./bin/int_test-41 >> test/results.csv
./bin/int_test-42 >> test/results.csv
./bin/int_test-43 >> test/results.csv
./bin/int_test-44 >> test/results.csv
./bin/int_test-45 >> test/results.csv
./bin/int_test-46 >> test/results.csv
./bin/int_test-47 >> test/results.csv
./bin/int_test-48 >> test/results.csv
./bin/int_test-49 >> test/results.csv
./bin/int_test-50 >> test/results.csv
./bin/int_test-51 >> test/results.csv
./bin/int_test-52 >> test/results.csv
./bin/int_test-53 >> test/results.csv
./bin/int_test-54 >> test/results.csv
./bin/int_test-55 >> test/results.csv
./bin/int_test-56 >> test/results.csv
./bin/int_test-57 >> test/results.csv
./bin/int_test-58 >> test/results.csv
./bin/int_test-59 >> test/results.csv
./bin/int_test-60 >> test/results.csv
./bin/int_test-61 >> test/results.csv
./bin/int_test-62 >> test/results.csv
./bin/int_test-63 >> test/results.csv
./bin/int_test-64 >> test/results.csv
./bin/int_test-65 >> test/results.csv
./bin/int_test-66 >> test/results.csv
./bin/int_test-67 >> test/results.csv
./bin/int_test-68 >> test/results.csv
./bin/int_test-69 >> test/results.csv
./bin/int_test-70 >> test/results.csv
./bin/int_test-71 >> test/results.csv
./bin/int_test-72 >> test/results.csv
./bin/int_test-73 >> test/results.csv
./bin/int_test-74 >> test/results.csv
./bin/int_test-75 >> test/results.csv
./bin/int_test-76 >> test/results.csv
./bin/int_test-77 >> test/results.csv
./bin/int_test-78 >> test/results.csv
./bin/int_test-79 >> test/results.csv
./bin/int_test-80 >> test/results.csv
./bin/int_test-81 >> test/results.csv
./bin/int_test-82 >> test/results.csv
./bin/int_test-83 >> test/results.csv
./bin/int_test-84 >> test/results.csv
./bin/int_test-85 >> test/results.csv
./bin/int_test-86 >> test/results.csv
./bin/int_test-87 >> test/results.csv
./bin/int_test-88 >> test/results.csv
./bin/int_test-89 >> test/results.csv
./bin/int_test-90 >> test/results.csv
./bin/int_test-91 >> test/results.csv
./bin/int_test-92 >> test/results.csv
./bin/int_test-93 >> test/results.csv
./bin/int_test-94 >> test/results.csv
./bin/int_test-95 >> test/results.csv
./bin/int_test-96 >> test/results.csv
./bin/int_test-97 >> test/results.csv
./bin/int_test-98 >> test/results.csv
./bin/int_test-99 >> test/results.csv
./bin/int_test-100 >> test/results.csv
./bin/int_test-101 >> test/results.csv
./bin/int_test-102 >> test/results.csv
./bin/int_test-103 >> test/results.csv
./bin/int_test-104 >> test/results.csv
./bin/int_test-105 >> test/results.csv
./bin/int_test-106 >> test/results.csv
./bin/int_test-107 >> test/results.csv
./bin/int_test-108 >> test/results.csv
./bin/int_test-109 >> test/results.csv
./bin/int_test-110 >> test/results.csv
./bin/int_test-111 >> test/results.csv
./bin/int_test-112 >> test/results.csv
./bin/int_test-113 >> test/results.csv
./bin/int_test-114 >> test/results.csv
./bin/int_test-115 >> test/results.csv
./bin/int_test-116 >> test/results.csv
./bin/int_test-117 >> test/results.csv
./bin/int_test-118 >> test/results.csv
./bin/int_test-119 >> test/results.csv
./bin/int_test-120 >> test/results.csv
./bin/int_test-121 >> test/results.csv
./bin/int_test-122 >> test/results.csv
./bin/int_test-123 >> test/results.csv
./bin/int_test-124 >> test/results.csv
./bin/int_test-125 >> test/results.csv
./bin/int_test-126 >> test/results.csv
./bin/int_test-127 >> test/results.csv
./bin/int_test-128 >> test/results.csv
./bin/int_test-129 >> test/results.csv
./bin/int_test-130 >> test/results.csv
./bin/int_test-131 >> test/results.csv
./bin/int_test-132 >> test/results.csv
./bin/int_test-133 >> test/results.csv
./bin/int_test-134 >> test/results.csv
./bin/int_test-135 >> test/results.csv
./bin/int_test-136 >> test/results.csv
./bin/int_test-137 >> test/results.csv
./bin/int_test-138 >> test/results.csv
./bin/int_test-139 >> test/results.csv
./bin/int_test-140 >> test/results.csv
./bin/int_test-141 >> test/results.csv
./bin/int_test-142 >> test/results.csv
./bin/int_test-143 >> test/results.csv
./bin/int_test-144 >> test/results.csv
./bin/int_test-145 >> test/results.csv
./bin/int_test-146 >> test/results.csv
./bin/int_test-147 >> test/results.csv
./bin/int_test-148 >> test/results.csv
./bin/int_test-149 >> test/results.csv
./bin/int_test-150 >> test/results.csv
./bin/int_test-151 >> test/results.csv
./bin/int_test-152 >> test/results.csv
./bin/int_test-153 >> test/results.csv
./bin/int_test-154 >> test/results.csv
./bin/int_test-155 >> test/results.csv
./bin/int_test-156 >> test/results.csv
./bin/int_test-157 >> test/results.csv
./bin/int_test-158 >> test/results.csv
./bin/int_test-159 >> test/results.csv
./bin/int_test-160 >> test/results.csv
./bin/int_test-161 >> test/results.csv
./bin/int_test-162 >> test/results.csv
./bin/int_test-163 >> test/results.csv
./bin/int_test-164 >> test/results.csv
./bin/int_test-165 >> test/results.csv
./bin/int_test-166 >> test/results.csv
./bin/int_test-167 >> test/results.csv
./bin/int_test-168 >> test/results.csv
./bin/int_test-169 >> test/results.csv
./bin/int_test-170 >> test/results.csv
./bin/int_test-171 >> test/results.csv
./bin/int_test-172 >> test/results.csv
./bin/int_test-173 >> test/results.csv
./bin/int_test-174 >> test/results.csv
./bin/int_test-175 >> test/results.csv
./bin/int_test-176 >> test/results.csv
./bin/int_test-177 >> test/results.csv
./bin/int_test-178 >> test/results.csv
./bin/int_test-179 >> test/results.csv
./bin/int_test-180 >> test/results.csv
./bin/int_test-181 >> test/results.csv
./bin/int_test-182 >> test/results.csv
./bin/int_test-183 >> test/results.csv
./bin/int_test-184 >> test/results.csv
./bin/int_test-185 >> test/results.csv
./bin/int_test-186 >> test/results.csv
./bin/int_test-187 >> test/results.csv
./bin/int_test-188 >> test/results.csv
./bin/int_test-189 >> test/results.csv
./bin/int_test-190 >> test/results.csv
./bin/int_test-191 >> test/results.csv
./bin/int_test-192 >> test/results.csv
./bin/int_test-193 >> test/results.csv
./bin/int_test-194 >> test/results.csv
./bin/int_test-195 >> test/results.csv
./bin/int_test-196 >> test/results.csv
./bin/int_test-197 >> test/results.csv
./bin/int_test-198 >> test/results.csv
./bin/int_test-199 >> test/results.csv
./bin/int_test-200 >> test/results.csv
./bin/int_test-201 >> test/results.csv
./bin/int_test-202 >> test/results.csv
./bin/int_test-203 >> test/results.csv
./bin/int_test-204 >> test/results.csv
./bin/int_test-205 >> test/results.csv
./bin/int_test-206 >> test/results.csv
./bin/int_test-207 >> test/results.csv
./bin/int_test-208 >> test/results.csv
./bin/int_test-209 >> test/results.csv
./bin/int_test-210 >> test/results.csv
